/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import visão.ClasePrincipal;

import java.io.BufferedReader;   
import java.io.File;   
import java.io.FileNotFoundException;   
import java.io.FileReader;   
import java.io.IOException;   
import java.util.Scanner;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.LineNumberReader;
import java.util.StringTokenizer;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
//import javax.swing.table.DefaultTableModel;

//import com.sun.xml.internal.bind.v2.schemagen.xmlschema.ExplicitGroup;
//import javax.swing.JOptionPane;

public class TelaRelatorioCistema extends javax.swing.JFrame {

    private  static String nome,data,hora,valor;
    
    public TelaRelatorioCistema() {
        initComponents();
        
        
        
        
        jButton1.setBackground(new java.awt.Color(0,0,0,0));
        jButton2.setBackground(new java.awt.Color(0,0,0,0));
        jButton3.setBackground(new java.awt.Color(0,0,0,0));
        jButton4.setBackground(new java.awt.Color(0,0,0,0));
        jButton5.setBackground(new java.awt.Color(0,0,0,0));
       // jPanel6.setBackground(new java.awt.Color(0,0,0,0));
 
    }
    
    private void calcular()
    {
        
     // fuçao para caucular o subtotal 
        float suma = 0;
        for( int i = 0; i < jTable1.getRowCount(); i++)
        {
            float renglon;
            renglon = Float.parseFloat(jTable1.getValueAt(i, 0).toString());
            
            suma = suma + renglon;
            
        }

         jLabel68.setText(String.valueOf(suma));
         jTextField2.setText(String.valueOf(suma));
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMelhorHora = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPiorHora2 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Pedidos");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(90, 440, 182, 40);

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(90, 510, 182, 40);

        jPanel3.setBackground(java.awt.Color.white);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Total de Clientes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel2)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(400, 70, 180, 200);

        jPanel4.setBackground(java.awt.Color.white);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Pedidos Feitos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel5)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(61, 61, 61))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(660, 60, 190, 210);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Geral");
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 190, 182, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Faturamento");
        getContentPane().add(jButton2);
        jButton2.setBounds(102, 279, 160, 31);

        jPanel5.setBackground(java.awt.Color.white);

        jLabel68.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel68.setText("0");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Faturamento");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel68)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel68)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(930, 60, 180, 220);

        jLabel20.setText("jLabel20");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(1040, 540, 40, 14);

        jLabel22.setText("jLabel21");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(1040, 620, 40, 14);

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(630, 370, 80, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Melhor dia da semana   =");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(424, 362, 190, 30);

        txtMelhorHora.setText("jLabel9");
        getContentPane().add(txtMelhorHora);
        txtMelhorHora.setBounds(660, 450, 70, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Melhor hora de compras   =");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 450, 222, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Cliente que mais pediu   =");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(430, 540, 224, 22);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Nome ...");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(660, 540, 374, 22);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Cliente que mais pagou   =");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(430, 602, 216, 40);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Nome ...");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(660, 610, 380, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Pior dia   =");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(840, 360, 198, 22);

        jLabel13.setText("jLabel9");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(1060, 360, 34, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Pior hora   = ");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(840, 450, 192, 22);

        jButton3.setText("jButton3");
        jButton3.setBorder(null);
        getContentPane().add(jButton3);
        jButton3.setBounds(100, 360, 170, 30);

        jTextField1.setBorder(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(250, 80, 0, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 700, 10, 0);

        jTextField2.setBorder(null);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(340, 510, 0, 40);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/5.png"))); // NOI18N
        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel11MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 4, 1300, 700);

        txtPiorHora2.setText("jLabel9");
        getContentPane().add(txtPiorHora2);
        txtPiorHora2.setBounds(1080, 440, 34, 14);

        setSize(new java.awt.Dimension(1316, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try{
             String filePath = ("C:\\Arquivos do programa/ValorTotal.txt");
        File file = new File(filePath);
            
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setColumnIdentifiers(columnsName);
            
              
            Object[] tableLines = br.lines().toArray();
            //model.addRow(tableLines);
            
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(";");
            //    integer[] valoresint = new integer(dataRow.length);
                model.addRow(dataRow);
                
                
              
                
                
                
                int[] a = new int[20];
                String varifica  = dataRow[0];
                String res1 = varifica.split("\\.")[0];
                
                String varifica2  = dataRow[1];
                String res2 = varifica2.split("\\.")[0];
                
                String varifica3  = dataRow[2];
                String res3 = varifica3.split("\\.")[0];
                
                String varifica4  = dataRow[3];
                String res4 = varifica4.split("\\.")[0];
                
                String varifica5  = dataRow[4];
                String res5 = varifica5.split("\\.")[0];
                
                String varifica6  = dataRow[5];
                String res6 = varifica6.split("\\.")[0];
                
                String varifica7  = dataRow[6];
                String res7 = varifica7.split("\\.")[0];
                
                String varifica8  = dataRow[7];
                String res8 = varifica8.split("\\.")[0];
                
                String varifica9  = dataRow[8];
                String res9 = varifica9.split("\\.")[0];
                
                String varifica10  = dataRow[9];
                String res10 = varifica10.split("\\.")[0];
                
                String varifica11  = dataRow[10];
                String res11 = varifica11.split("\\.")[0];
                
                String varifica12  = dataRow[11];
                String res12 = varifica12.split("\\.")[0];
                
                String varifica13  = dataRow[12];
                String res13 = varifica13.split("\\.")[0];
                
                String varifica14  = dataRow[13];
                String res14 = varifica14.split("\\.")[0];
                
                String varifica15  = dataRow[14];
                String res15 = varifica15.split("\\.")[0];
                
                String varifica16  = dataRow[15];
                String res16 = varifica16.split("\\.")[0];
                
                String varifica17  = dataRow[16];
                String res17 = varifica17.split("\\.")[0];
                
                String varifica18  = dataRow[17];
                String res18 = varifica18.split("\\.")[0];
                
                String varifica19  = dataRow[18];
                String res19 = varifica19.split("\\.")[0];
                
                String varifica20  = dataRow[19];
                String res20 = varifica20.split("\\.")[0];
                
                int um = Integer.parseInt(res1);
                int dois = Integer.parseInt(res2);
                int tres = Integer.parseInt(res3);
                int quatro = Integer.parseInt(res4);
                int cinco = Integer.parseInt(res5);
                int seis = Integer.parseInt(res6);
                int sete =  Integer.parseInt(res7);
               int oito = Integer.parseInt(res8);
                int nove = Integer.parseInt(res9);
                int dez = Integer.parseInt(res10);
                int onze = Integer.parseInt(res11);
                int doze  = Integer.parseInt(res12);
                int treze = Integer.parseInt(res13);
                int quatorze  = Integer.parseInt(res14);
                int quise  = Integer.parseInt(res15);
                int deseseis = Integer.parseInt(res16);
                int desesete = Integer.parseInt(res17);
                int desoto  = Integer.parseInt(res18);
                int desenove  = Integer.parseInt(res19);
                int vinte = Integer.parseInt(res20); 
                
               
            int[] meuArray = new int[10];
                
                if(um != 0){
                //NAO TEM ZERO
                meuArray[0] = um;                   
                }else{} 
                
                
                
                if(dois != 0){
                //NAO TEM ZERO
                meuArray[1] = dois;                   
                }else{}
                
                if(tres != 0){
                //NAO TEM ZERO
                meuArray[2] = tres;                   
                }else{} 
                
                if(quatro != 0){
                //NAO TEM ZERO
                meuArray[1] = quatro;                   
                }else{}
                
                if(cinco != 0){
                //NAO TEM ZERO
                meuArray[1] = cinco;                   
                }else{}
                
                if(seis != 0){
                //NAO TEM ZERO
                meuArray[0] = seis;                   
                }else{} 
                
                if(sete != 0){
                //NAO TEM ZERO
                meuArray[1] = sete;                   
                }else{}
                
                if(oito != 0){
                //NAO TEM ZERO
                meuArray[2] = oito;                   
                }else{} 
                
                if(nove != 0){
                //NAO TEM ZERO
                meuArray[1] = nove;                   
                }else{}
                
                if(dez != 0){
                //NAO TEM ZERO
                meuArray[1] = dez;                   
                }else{}
                
                
                 if(onze != 0){
                //NAO TEM ZERO
                meuArray[0] = onze;                   
                }else{} 
                
                if(doze != 0){
                //NAO TEM ZERO
                meuArray[1] = doze;                   
                }else{}
                
                if(treze != 0){
                //NAO TEM ZERO
                meuArray[2] = treze;                   
                }else{} 
                
                if(quatorze != 0){
                //NAO TEM ZERO
                meuArray[1] = quatorze;                   
                }else{}
                
                if(quise != 0){
                //NAO TEM ZERO
                meuArray[1] = quise;                   
                }else{}
                
                if(deseseis != 0){
                //NAO TEM ZERO
                meuArray[0] = deseseis;                   
                }else{} 
                
                if(desesete != 0){
                //NAO TEM ZERO
                meuArray[1] = desesete;                   
                }else{}
                
                if(desoto != 0){
                //NAO TEM ZERO
                meuArray[2] = desoto;                   
                }else{} 
                
                if(desenove != 0){
                //NAO TEM ZERO
                meuArray[1] = desenove;                   
                }else{}
                
                if(vinte != 0){
                //NAO TEM ZERO
                meuArray[1] = vinte;                   
                }else{}
                
                 int Contador = 0;
               for (int j = 0; j < meuArray.length; j ++){
                if (dataRow[j] != null)
                Contador ++;
                jLabel4.setText(""+Contador);
                //jTextField1.setText(""+contador);
                
                System.out.print(""+Contador);
               }
                 
                 
                
        //  int total = um +dois+ tres + quatro + cinco + seis + sete + oito +
        //          nove + dez + onze + doze  + treze + quatoze + quise +deseseis +desesete + desoto +desenove + vinte;
          
          int total1 = um +dois+ tres + quatro + cinco + seis + sete + oito +
                  nove + dez + onze + doze  + treze + quatorze + quise +deseseis +desesete + desoto;
        //         System.out.print(um);
              //  jLabel68.setText(""+total);
               // jTextField1.setText(""+total);
                 
               
               int contador = 0;
               for (int j = 0; j < dataRow.length; j ++){
                if (dataRow[j] != null)
                contador ++;
              //  jLabel4.setText(""+contador);
                jTextField1.setText(""+contador);
                
                System.out.print(""+contador);
               } int bloco = Integer.parseInt(jTextField1.getText());
               
               
              
              if(bloco != 20){
                   //18
                //   jLabel68.setText(""+total1);

               }else{
                   //20
                   
                  int total = um +dois+ tres + quatro + cinco + seis + sete + oito +
                  nove + dez + onze + doze  + treze + quatorze + quise +deseseis +desesete + desoto +desenove + vinte;
                  // jLabel68.setText(""+total);
               } 
               
          
                     
              
               


             /*  String um =  jTextField8.getText();
               String dois = jTextField9.getText();
               String tres = jTextField10.getText();
               String quatro = jTextField11.getText();
               
               int UM = Integer.parseInt(um);
               int DOIS = Integer.parseInt(dois);
               int TRES =  Integer.parseInt(tres);
               int QUATRO =  Integer.parseInt(quatro);
               int RESUTADO = UM * DOIS;
               System.out.print(RESUTADO);
               jTextField12.setText(""+RESUTADO); */
             
            }
            
        }catch (Exception ex) {
            Logger.getLogger(PaginaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        try {
			//abre o arquivo
			FileReader fr = new FileReader("C:\\Arquivos do programa/textando.txt");
			BufferedReader br = new BufferedReader(fr);
			String temp;
			//A cada interação, é uma linha do arquivo e atribui-a a temp
			while ((temp = br.readLine()) != null)
			{
				//Aqui gera a sua "lista". No caso, imprimi cada linha na tela.
				String[] a = temp.split(";");
				int i=0;
				for(String each : a)
				{
					/*if(i==0){
						nome=each;							
						System.out.println(nome);
					}*/
						/*if(i==1){
							data=each;
							//System.out.println(data);
                                                        jLabel9.setText(data);
						} 
						if(i==2){
							hora=each;
							i=-1;
							//System.out.println(hora);
                                                        txtMelhorHora.setText(hora);
                                                        
                                                        }*/
                                                if(i==1){
                                                        nome=each;
                                                        i=-1;
                                                       //System.out.println(TOt);
                                                        jLabel18.setText("nome");
                                                        jLabel21.setText("nome");
                                                
                                                }
                                                        
						i++;
					}						
				}
		}
		catch (FileNotFoundException el)
		{
			System.out.println("Arquivo não Encontrado!");
		} 
		catch (IOException e) 
		{
			e.printStackTrace();
		}
        
        // VALOR 
        try {
			//abre o arquivo
			FileReader fr = new FileReader("C:\\Arquivos do programa/textando.txt");
			BufferedReader br = new BufferedReader(fr);
			String temp;
			//A cada interação, é uma linha do arquivo e atribui-a a temp
			while ((temp = br.readLine()) != null)
			{
				//Aqui gera a sua "lista". No caso, imprimi cada linha na tela.
				String[] a = temp.split(";");
				int i=0;
				for(String each : a)
				{
					/*if(i==0){
						nome=each;							
						System.out.println(nome);
					}*/
						/*if(i==1){
							data=each;
							//System.out.println(data);
                                                        jLabel9.setText(data);
						} 
						if(i==2){
							hora=each;
							i=-1;
							//System.out.println(hora);
                                                        txtMelhorHora.setText(hora);
                                                        
                                                        }*/
                                                if(i==9){
                                                        valor=each;
                                                        i=-1;
                                                       //System.out.println(TOt);
                                                      //  jLabel68.setText(valor);
                                                
                                                }
                                                        
						i++;
					}						
				}
		}
		catch (FileNotFoundException el)
		{
			System.out.println("Arquivo não Encontrado!");
		} 
		catch (IOException e) 
		{
			e.printStackTrace();
		}


        // MELHOR HORA
        try {
			//abre o arquivo
			FileReader fr = new FileReader("C:\\Arquivos do programa/textando.txt");
			BufferedReader br = new BufferedReader(fr);
			String temp;
			//A cada interação, é uma linha do arquivo e atribui-a a temp
			while ((temp = br.readLine()) != null)
			{
				//Aqui gera a sua "lista". No caso, imprimi cada linha na tela.
				String[] a = temp.split(";");
				int i=0;
				for(String each : a)
				{
					/*if(i==0){
						nome=each;							
						System.out.println(nome);
					}*/
						if(i==1){
							data=each;
							//System.out.println(data);
                                                        jLabel9.setText(data);
						} 
						if(i==2){
							hora=each;
							i=-1;
							//System.out.println(hora);
                                                        txtMelhorHora.setText(hora);
                                                        
						}
						i++;
					}						
				}
		}
		catch (FileNotFoundException el)
		{
			System.out.println("Arquivo não Encontrado!");
		} 
		catch (IOException e) 
		{
			e.printStackTrace();
		}


        //MELHOR DATA
        
        try {
			//abre o arquivo
			FileReader fr = new FileReader("textando.txt");
			BufferedReader br = new BufferedReader(fr);
			String temp;
			//A cada interação, é uma linha do arquivo e atribui-a a temp
			while ((temp = br.readLine()) != null)
			{
				//Aqui gera a sua "lista". No caso, imprimi cada linha na tela.
				String[] a = temp.split(";");
				int i=0;
				for(String each : a)
				{
					/*if(i==0){
						nome=each;							
						System.out.println(nome);
					}*/
						if(i==1){
							data=each;
							//System.out.println(data);
                                                        jLabel9.setText(data);
						} /*
						if(i==2){
							valor=each;
							i=-1;
							System.out.println(valor);
                                                        
						}*/
						i++;
					}						
				}
		}
		catch (FileNotFoundException el)
		{
			System.out.println("Arquivo não Encontrado!");
		} 
		catch (IOException e) 
		{
			e.printStackTrace();
		}
        
        //PEDIDOS FEITOS
        File arquivo = new File ("C:\\Arquivos do programa/textando.txt");
    
        try {
            FileReader fr = new FileReader(arquivo);
            BufferedReader br = new BufferedReader(fr);
            //String linha = br.readLine();
            String d;  //new
            
            Object[] tableLines = br.lines().toArray();
            
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(";");
                
                
            }
            while((d=br.readLine())!=null){
                StringTokenizer dato = new StringTokenizer(d,";");
                Vector x = new Vector();
                while(dato.hasMoreTokens()){
                    x.addElement(dato.nextToken());
                }
              // jLabel11.setText(x.toString());
               
            }
            fr.close();
        } catch (Exception ex) {
            Logger.getLogger(PerfilDoCliente.class.getName()).log(Level.SEVERE, null, ex);

        }
        
        
        //PEDIDOS FEITOS
        LineNumberReader lnrR = null;
        try {
            String filePath = ("C:\\Arquivos do programa/textando.txt");
            File file = new File(filePath);
            lnrR = new LineNumberReader(new FileReader(file));
            try {
                lnrR.skip(Long.MAX_VALUE);
            } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioCistema.class.getName()).log(Level.SEVERE, null, ex);
            }
            int retorno = lnrR.getLineNumber();
            String rere = Integer.toString(retorno);
         //   jLabel4.setText(rere);
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaRelatorioCistema.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                lnrR.close();
            } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioCistema.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
       //TOTAL DE CLIENTES 
       LineNumberReader lnr = null;
        try {
            String filePath = ("C://Users/henrique matheus/Documents/NetBeansProjects/AplicacaoAnbiente/Alumnos.txt");
            File file = new File(filePath);
            lnr = new LineNumberReader(new FileReader(file));
            try {
                lnr.skip(Long.MAX_VALUE);
            } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioCistema.class.getName()).log(Level.SEVERE, null, ex);
            }
            int retorno = lnr.getLineNumber();
            String rere = Integer.toString(retorno);
           jLabel2.setText(rere);
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaRelatorioCistema.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                lnr.close();
            } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioCistema.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        //metodo de caucular o total
        calcular();
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     JanelaDoGraficoLanche Tela = new JanelaDoGraficoLanche();
     Tela.setVisible(rootPaneCheckingEnabled);
     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel11MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseMoved
        // TODO add your handling code here:
         //metodo de caucular o total
          calcular();
        
    }//GEN-LAST:event_jLabel11MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioCistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioCistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioCistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioCistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorioCistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel txtMelhorHora;
    private javax.swing.JLabel txtPiorHora2;
    // End of variables declaration//GEN-END:variables
}
