/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.LineNumberReader;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.layout.Background;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;





    
public class TelaPrincipal extends javax.swing.JFrame {




    private  static String nome,data,hora,valor;
    
    public TelaPrincipal() {
        initComponents();
        
        jButton3.setBackground(new java.awt.Color(0,0,0,0));
        jButton4.setBackground(new java.awt.Color(0,0,0,0));
       jButtonNegocio.setBackground(new java.awt.Color(0,0,0,0));
        jToggleButton1.setBackground(new java.awt.Color(0,0,0,0));
       jButton5.setBackground(new java.awt.Color(0,0,0,0));
       jButton8.setBackground(new java.awt.Color(0,0,0,0));
       jButton1.setBackground(new java.awt.Color(0,0,0,0));
       
       


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jldata = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadUsuario = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTelaBemVindo = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlhora = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        TxT_Pedididos = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabelaP = new javax.swing.JTable();
        txT_Total = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txT_Faturamento = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextpro = new javax.swing.JTextField();
        jButtonNegocio = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jldata.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jldata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenuCadastro.setText("Cadratro");

        jMenuItemCadUsuario.setText("Usuarios");
        jMenuItemCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadUsuario);

        jMenuBar1.add(jMenuCadastro);

        jMenuRelatorios.setText("Relatorios");
        jMenuBar1.add(jMenuRelatorios);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTelaBemVindo.setText("Tela de Bem vindo");
        jMenuItemTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTelaBemVindo);

        jMenuBar1.add(jMenuFerramentas);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Pesquisar por Cliente / Buscar");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Adicionar");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Meu negocio");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Ver Lista Completa");

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("?");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Estatisticas");

        jLabel11.setText("Ajuda");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlhora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlhora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("PedidosFeitos ");
        jPanel2.add(jLabel13);

        TxT_Pedididos.setText("jLabel1");
        jPanel2.add(TxT_Pedididos);

        jButton9.setText("relatorio");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("relatorio");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(84, 93, 106));
        setExtendedState(MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel12.setText("Total de Cliente");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(610, 60, 75, 14);

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(120, 490, 80, 80);

        jtTabelaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome"
            }
        ));
        jtTabelaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTabelaPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTabelaP);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(410, 380, 670, 280);

        txT_Total.setText("0");
        getContentPane().add(txT_Total);
        txT_Total.setBounds(610, 110, 80, 40);

        jLabel14.setText("Faturamento");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(780, 60, 62, 14);

        txT_Faturamento.setText("0");
        getContentPane().add(txT_Faturamento);
        txT_Faturamento.setBounds(770, 120, 90, 14);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1010, 270, 70, 70);

        jTextpro.setBackground(new java.awt.Color(83, 93, 106));
        jTextpro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextpro.setBorder(null);
        jTextpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextproActionPerformed(evt);
            }
        });
        getContentPane().add(jTextpro);
        jTextpro.setBounds(440, 290, 530, 40);

        jButtonNegocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNegocioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNegocio);
        jButtonNegocio.setBounds(1170, 620, 80, 70);

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(120, 290, 80, 80);

        jButton3.setForeground(new java.awt.Color(153, 255, 255));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(120, 190, 80, 80);

        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(120, 590, 80, 80);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 390, 80, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fundinho.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1320, -100, 120, 1400);

        jLabel15.setText("Total de pedidos");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(450, 60, 90, 14);

        jLabel16.setText("0");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(460, 120, 60, 14);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1010, 210, 73, 23);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Tela inicial - 1300x700.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-190, 0, 1730, 680);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fundinho.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 670, 1400, 1220);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fundinho.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 670, 120, 1220);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fundinho.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-10, -6, 40, 690);

        setSize(new java.awt.Dimension(1348, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBemVindoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemTelaBemVindoActionPerformed

    private void jMenuItemCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadUsuarioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      JFCadrastro Tela = new JFCadrastro();
        Tela.setVisible(rootPaneCheckingEnabled);  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           PaginaUsuario Tela = new PaginaUsuario();
        Tela.setVisible(rootPaneCheckingEnabled);   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try {
             String filePath = ("C:\\Arquivos do programa/ValorTotal.txt");
        File file = new File(filePath);
            
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
        //    DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
          //  model.setColumnIdentifiers(columnsName);
            
              
            Object[] tableLines = br.lines().toArray();
            //model.addRow(tableLines);
            
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(";");
              //  model.addRow(dataRow);
              
                int um = Integer.parseInt(dataRow[0]);
                int dois = Integer.parseInt(dataRow[1]);
                int tres = Integer.parseInt(dataRow[2]);
                int quatro = Integer.parseInt(dataRow[3]);
                int cinco = Integer.parseInt(dataRow[4]);
                int seis= Integer.parseInt(dataRow[5]);
                int sete = Integer.parseInt(dataRow[6]);
               int oito = Integer.parseInt(dataRow[7]);
                int nove = Integer.parseInt(dataRow[8]);
                int dez = Integer.parseInt(dataRow[9]);
                int onze = Integer.parseInt(dataRow[10]);
                int doze = Integer.parseInt(dataRow[11]);
                int treze = Integer.parseInt(dataRow[12]);
                int quatoze = Integer.parseInt(dataRow[13]);
                int quise= Integer.parseInt(dataRow[14]);
                int deseseis = Integer.parseInt(dataRow[15]);
               int desesete = Integer.parseInt(dataRow[16]);
                int desoto = Integer.parseInt(dataRow[17]);
                int desenove = Integer.parseInt(dataRow[18]);
                 int vinte = Integer.parseInt(dataRow[19]); 
                 
                 int[] MeuArray = new int[10];
                
                if(um != 0){
                //NAO TEM ZERO
                MeuArray[0] = um;                   
                }else{} 
                
                if(dois != 0){
                //NAO TEM ZERO
                MeuArray[1] = dois;                   
                }else{}
                
                if(tres != 0){
                //NAO TEM ZERO
                MeuArray[2] = tres;                   
                }else{} 
                
                if(quatro != 0){
                //NAO TEM ZERO
                MeuArray[1] = quatro;                   
                }else{}
                
                if(cinco != 0){
                //NAO TEM ZERO
                MeuArray[1] = cinco;                   
                }else{}
                
                if(seis != 0){
                //NAO TEM ZERO
                MeuArray[0] = seis;                   
                }else{} 
                
                if(sete != 0){
                //NAO TEM ZERO
                MeuArray[1] = sete;                   
                }else{}
                
                if(oito != 0){
                //NAO TEM ZERO
                MeuArray[2] = oito;                   
                }else{} 
                
                if(nove != 0){
                //NAO TEM ZERO
                MeuArray[1] = nove;                   
                }else{}
                
                if(dez != 0){
                //NAO TEM ZERO
                MeuArray[1] = dez;                   
                }else{}
                
                
                 if(onze != 0){
                //NAO TEM ZERO
                MeuArray[0] = onze;                   
                }else{} 
                
                if(doze != 0){
                //NAO TEM ZERO
                MeuArray[1] = doze;                   
                }else{}
                
                if(treze != 0){
                //NAO TEM ZERO
                MeuArray[2] = treze;                   
                }else{} 
                
                if(quatoze != 0){
                //NAO TEM ZERO
                MeuArray[1] = quatoze;                   
                }else{}
                
                if(quise != 0){
                //NAO TEM ZERO
                MeuArray[1] = quise;                   
                }else{}
                
                if(deseseis != 0){
                //NAO TEM ZERO
                MeuArray[0] = deseseis;                   
                }else{} 
                
                if(desesete != 0){
                //NAO TEM ZERO
                MeuArray[1] = desesete;                   
                }else{}
                
                if(desoto != 0){
                //NAO TEM ZERO
                MeuArray[2] = desoto;                   
                }else{} 
                
                if(desenove != 0){
                //NAO TEM ZERO
                MeuArray[1] = desenove;                   
                }else{}
                
                if(vinte != 0){
                //NAO TEM ZERO
                MeuArray[1] = vinte;                   
                }else{}
                
                 int Contador = 0;
               for (int j = 0; j < MeuArray.length; j ++){
                if (dataRow[j] != null)
                Contador ++;
                jLabel16.setText(""+Contador);
                //jTextField1.setText(""+contador);
                
                System.out.print(""+Contador);
               }
            }
            
        } catch (Exception ex) {
            Logger.getLogger(PaginaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

        
 
        
        
        try {
             String filePath = ("C:\\Arquivos do programa/ValorTotal.txt");
        File file = new File(filePath);
            
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
        //    DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
          //  model.setColumnIdentifiers(columnsName);
            
              
            Object[] tableLines = br.lines().toArray();
            //model.addRow(tableLines);
            
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(";");
              //  model.addRow(dataRow);
              
                int um = Integer.parseInt(dataRow[0]);
                int dois = Integer.parseInt(dataRow[1]);
                int tres = Integer.parseInt(dataRow[2]);
                int quatro = Integer.parseInt(dataRow[3]);
                int cinco = Integer.parseInt(dataRow[4]);
                int seis= Integer.parseInt(dataRow[5]);
                int sete = Integer.parseInt(dataRow[6]);
               int oito = Integer.parseInt(dataRow[7]);
                int nove = Integer.parseInt(dataRow[8]);
                int dez = Integer.parseInt(dataRow[9]);
                int onze = Integer.parseInt(dataRow[10]);
                int doze = Integer.parseInt(dataRow[11]);
                int treze = Integer.parseInt(dataRow[12]);
                int quatoze = Integer.parseInt(dataRow[13]);
                int quise= Integer.parseInt(dataRow[14]);
                int deseseis = Integer.parseInt(dataRow[15]);
               int desesete = Integer.parseInt(dataRow[16]);
                int desoto = Integer.parseInt(dataRow[17]);
                int desenove = Integer.parseInt(dataRow[18]);
                 int vinte = Integer.parseInt(dataRow[19]); 
               
                 
         
          int total = um +dois+ tres + quatro + cinco + seis + sete + oito +
                  nove + dez + onze + doze  + treze + quatoze + quise +deseseis +desesete + desoto +desenove + vinte;
            //     System.out.print(um);
                txT_Faturamento.setText("R$"+total);
               
            /* int soma = 0;

             for (int i=0; i < 19; i++) {
             soma+=dataRow[i];
             } */
                
                
                
           


             /*  String um =  jTextField8.getText();
               String dois = jTextField9.getText();
               String tres = jTextField10.getText();
               String quatro = jTextField11.getText();
               
               int UM = Integer.parseInt(um);
               int DOIS = Integer.parseInt(dois);
               int TRES =  Integer.parseInt(tres);
               int QUATRO =  Integer.parseInt(quatro);
               int RESUTADO = UM * DOIS;
               System.out.print(RESUTADO);
               jTextField12.setText(""+RESUTADO); */
             
            }
            
        } catch (Exception ex) {
            Logger.getLogger(PaginaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } 
        /* int resposta;
   
          resposta = JOptionPane.showConfirmDialog(null, "quer enviar mensagem para o aniiversariante?");
        if(resposta == JOptionPane.YES_OPTION){
        URI link = null;  
       try {
      link = new URI("https://api.whatsapp.com/send?phone=5583998692594&text=é+a+hora+da+putaria");
     // Desktop.getDesktop().browse(link);
    } catch (URISyntaxException ex) {
   Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
   }
   try {
  Desktop.getDesktop().browse(link);
  } catch (IOException ex) {
  Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
  } */
        
        
         //TOTAL DE pedidos
       LineNumberReader lnr = null;
        try {
            String filePath = ("C:\\Arquivos do programa/textando.txt");
            File file = new File(filePath);
            lnr = new LineNumberReader(new FileReader(file));
            try {
                lnr.skip(Long.MAX_VALUE);
            } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioCistema.class.getName()).log(Level.SEVERE, null, ex);
            }
            int retorno = lnr.getLineNumber();
            String rere = Integer.toString(retorno);
            //jLabel16.setText(rere);
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaRelatorioCistema.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                lnr.close();
            } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioCistema.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        //VALOR ARRECADADO
        try {
			//abre o arquivo
			FileReader fr = new FileReader("C:\\Arquivos do programa/textando.txt");
			BufferedReader br = new BufferedReader(fr);
			String temp;
			//A cada interação, é uma linha do arquivo e atribui-a a temp
			while ((temp = br.readLine()) != null)
			{
				//Aqui gera a sua "lista". No caso, imprimi cada linha na tela.
				String[] a = temp.split(";");
				int i=0;
				for(String each : a)
				{
					/*if(i==0){
						nome=each;							
						System.out.println(nome);
					}*/
						/*if(i==1){
							data=each;
							//System.out.println(data);
                                                        jLabel9.setText(data);
						} 
						if(i==2){
							hora=each;
							i=-1;
							//System.out.println(hora);
                                                        txtMelhorHora.setText(hora);
                                                        
                                                        }*/
                                                if(i==12){
                                                        valor=each;
                                                        i=-1;
                                                        
                                                        
                                                      // System.out.print(valor);
                                                       
                                                      
                                                        
                                                
                                                }
                                                        
						i++;
					}						
				}
		}
		catch (FileNotFoundException el)
		{
			System.out.println("Arquivo não Encontrado!");
		} 
		catch (IOException e) 
		{
			e.printStackTrace();
		}
        


        //PEDIDOS FEITOS
        LineNumberReader lnrR = null;
        try {
            String filePath = ("C:\\Arquivos do programa/texto.txt");
            File file = new File(filePath);
            lnrR = new LineNumberReader(new FileReader(file));
            try {
                lnrR.skip(Long.MAX_VALUE);
            } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioCistema.class.getName()).log(Level.SEVERE, null, ex);
            }
            int retorno = lnrR.getLineNumber();
            String rere = Integer.toString(retorno);
            txT_Total.setText(rere);
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaRelatorioCistema.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                lnrR.close();
            } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioCistema.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        







       
        
        
       
        //COREÇÃO DE TABELA 
   /* String filePath = ("C:\\Arquivos do programa/Texto.txt");
    File fie = new File(filePath);

    try {
        BufferedReader br = new BufferedReader(new FileReader(fie));
        String firstLine = br.readLine().trim();
        String[] columnsName = firstLine.split(",");
        DefaultTableModel model = (DefaultTableModel)jtTabelaP.getModel();
        //model.setColumnIdentifiers(columnsName);
        
        Object[] tableLines = br.lines().toArray();
        
        for(int i = 0; 1 < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                model.addRow(dataRow);
            }

        } catch (Exception ex) {
            Logger.getLogger(PaginaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }    */
      
    }//GEN-LAST:event_formWindowOpened

    private void jButtonNegocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNegocioActionPerformed
        MeuNegocio Tela = new MeuNegocio();
        Tela.setVisible(rootPaneCheckingEnabled); 
    }//GEN-LAST:event_jButtonNegocioActionPerformed

    private void jtTabelaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTabelaPMouseClicked
        PerfilDoCliente Tela = new PerfilDoCliente();
        Tela.setVisible(rootPaneCheckingEnabled);

        
    }//GEN-LAST:event_jtTabelaPMouseClicked

    private void jTextproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextproActionPerformed
        

    }//GEN-LAST:event_jTextproActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      DefaultTableModel model = (DefaultTableModel)jtTabelaP.getModel();
      TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
      jtTabelaP.setRowSorter(tr);
      tr.setRowFilter(RowFilter.regexFilter(jTextpro.getText().trim()));
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
  
               TelaRelatorioCistema Tela = new TelaRelatorioCistema();
        Tela.setVisible(rootPaneCheckingEnabled); 
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        frm_GuardarDados Tela = new frm_GuardarDados();
        Tela.setVisible(rootPaneCheckingEnabled);
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ListaVIP Tela = new ListaVIP();
       Tela.setVisible(rootPaneCheckingEnabled);
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        try {
             String filePath = ("C:\\Arquivos do programa/ValorTotal.txt");
        File file = new File(filePath);
            
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
        //    DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
          //  model.setColumnIdentifiers(columnsName);
            
              
            Object[] tableLines = br.lines().toArray();
            //model.addRow(tableLines);
            
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(";");
              //  model.addRow(dataRow);
              
                int um = Integer.parseInt(dataRow[0]);
                int dois = Integer.parseInt(dataRow[1]);
                int tres = Integer.parseInt(dataRow[2]);
                int quatro = Integer.parseInt(dataRow[3]);
                int cinco = Integer.parseInt(dataRow[4]);
                int seis= Integer.parseInt(dataRow[5]);
                int sete = Integer.parseInt(dataRow[6]);
               int oito = Integer.parseInt(dataRow[7]);
                int nove = Integer.parseInt(dataRow[8]);
                int dez = Integer.parseInt(dataRow[9]);
                int onze = Integer.parseInt(dataRow[10]);
                int doze = Integer.parseInt(dataRow[11]);
                int treze = Integer.parseInt(dataRow[12]);
                int quatoze = Integer.parseInt(dataRow[13]);
                int quise= Integer.parseInt(dataRow[14]);
                int deseseis = Integer.parseInt(dataRow[15]);
               int desesete = Integer.parseInt(dataRow[16]);
                int desoto = Integer.parseInt(dataRow[17]);
                int desenove = Integer.parseInt(dataRow[18]);
                 int vinte = Integer.parseInt(dataRow[19]); 
                 
                 int[] MeuArray = new int[10];
                
                if(um != 0){
                //NAO TEM ZERO
                MeuArray[0] = um;                   
                }else{} 
                
                if(dois != 0){
                //NAO TEM ZERO
                MeuArray[1] = dois;                   
                }else{}
                
                if(tres != 0){
                //NAO TEM ZERO
                MeuArray[2] = tres;                   
                }else{} 
                
                if(quatro != 0){
                //NAO TEM ZERO
                MeuArray[1] = quatro;                   
                }else{}
                
                if(cinco != 0){
                //NAO TEM ZERO
                MeuArray[1] = cinco;                   
                }else{}
                
                if(seis != 0){
                //NAO TEM ZERO
                MeuArray[0] = seis;                   
                }else{} 
                
                if(sete != 0){
                //NAO TEM ZERO
                MeuArray[1] = sete;                   
                }else{}
                
                if(oito != 0){
                //NAO TEM ZERO
                MeuArray[2] = oito;                   
                }else{} 
                
                if(nove != 0){
                //NAO TEM ZERO
                MeuArray[1] = nove;                   
                }else{}
                
                if(dez != 0){
                //NAO TEM ZERO
                MeuArray[1] = dez;                   
                }else{}
                
                
                 if(onze != 0){
                //NAO TEM ZERO
                MeuArray[0] = onze;                   
                }else{} 
                
                if(doze != 0){
                //NAO TEM ZERO
                MeuArray[1] = doze;                   
                }else{}
                
                if(treze != 0){
                //NAO TEM ZERO
                MeuArray[2] = treze;                   
                }else{} 
                
                if(quatoze != 0){
                //NAO TEM ZERO
                MeuArray[1] = quatoze;                   
                }else{}
                
                if(quise != 0){
                //NAO TEM ZERO
                MeuArray[1] = quise;                   
                }else{}
                
                if(deseseis != 0){
                //NAO TEM ZERO
                MeuArray[0] = deseseis;                   
                }else{} 
                
                if(desesete != 0){
                //NAO TEM ZERO
                MeuArray[1] = desesete;                   
                }else{}
                
                if(desoto != 0){
                //NAO TEM ZERO
                MeuArray[2] = desoto;                   
                }else{} 
                
                if(desenove != 0){
                //NAO TEM ZERO
                MeuArray[1] = desenove;                   
                }else{}
                
                if(vinte != 0){
                //NAO TEM ZERO
                MeuArray[1] = vinte;                   
                }else{}
                
                 int Contador = 0;
               for (int j = 0; j < MeuArray.length; j ++){
                if (dataRow[j] != null)
                Contador ++;
                jLabel16.setText(""+Contador);
                //jTextField1.setText(""+contador);
                
                System.out.print(""+Contador);
               }
            }
            
        } catch (Exception ex) {
            Logger.getLogger(PaginaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }



        
        
        
        
        while (jtTabelaP.getModel().getRowCount() > 0) {
    ((DefaultTableModel) jtTabelaP.getModel()).removeRow(0);
    }
        
        
         String filePath = ("C:\\Arquivos do programa/Texto.txt");
    File fie = new File(filePath);

    try {
        BufferedReader br = new BufferedReader(new FileReader(fie));
        String firstLine = br.readLine().trim();
        String[] columnsName = firstLine.split(",");
        DefaultTableModel model = (DefaultTableModel)jtTabelaP.getModel();
        //model.setColumnIdentifiers(columnsName);
        
        Object[] tableLines = br.lines().toArray();
        
        for(int i = 0; 1 < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                model.addRow(dataRow);
            }

        } catch (Exception ex) {
            Logger.getLogger(PaginaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    
    
         //tOTAL DE CLIENTES
        LineNumberReader lnrR = null;
        try {
            
            File file = new File(filePath);
            lnrR = new LineNumberReader(new FileReader(file));
            try {
                lnrR.skip(Long.MAX_VALUE);
            } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioCistema.class.getName()).log(Level.SEVERE, null, ex);
            }
            int retorno = lnrR.getLineNumber();
            String rere = Integer.toString(retorno);
            txT_Total.setText(rere);
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaRelatorioCistema.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                lnrR.close();
            } catch (IOException ex) {
                Logger.getLogger(TelaRelatorioCistema.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
        
       
        
             
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 try {
             String filePath = ("C:\\Arquivos do programa/ValorTotal.txt");
        File file = new File(filePath);
            
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
        //    DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
          //  model.setColumnIdentifiers(columnsName);
            
              
            Object[] tableLines = br.lines().toArray();
            //model.addRow(tableLines);
            
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(";");
              //  model.addRow(dataRow);
              
                int um = Integer.parseInt(dataRow[0]);
                int dois = Integer.parseInt(dataRow[1]);
                int tres = Integer.parseInt(dataRow[2]);
                int quatro = Integer.parseInt(dataRow[3]);
                int cinco = Integer.parseInt(dataRow[4]);
                int seis= Integer.parseInt(dataRow[5]);
                int sete = Integer.parseInt(dataRow[6]);
               int oito = Integer.parseInt(dataRow[7]);
                int nove = Integer.parseInt(dataRow[8]);
                int dez = Integer.parseInt(dataRow[9]);
                int onze = Integer.parseInt(dataRow[10]);
                int doze = Integer.parseInt(dataRow[11]);
                int treze = Integer.parseInt(dataRow[12]);
                int quatoze = Integer.parseInt(dataRow[13]);
                int quise= Integer.parseInt(dataRow[14]);
                int deseseis = Integer.parseInt(dataRow[15]);
               int desesete = Integer.parseInt(dataRow[16]);
                int desoto = Integer.parseInt(dataRow[17]);
                int desenove = Integer.parseInt(dataRow[18]);
                 int vinte = Integer.parseInt(dataRow[19]); 
                 
                
                 
                 
                int[] meuArray = new int[20];
               
        meuArray [0] = um;
        meuArray [1] = dois;
        meuArray [2] = tres;
        meuArray [3] = quatro;
        meuArray [4] = cinco;
        meuArray [5] = seis;
        meuArray [6] = sete;
        meuArray [7] = oito;
        meuArray [8] = nove;
        meuArray [9] = dez;
        meuArray [10] = onze;
        meuArray [11] = doze;
        meuArray [12] = treze;
        meuArray [13] = quatoze;
        meuArray [14] = quise;
        meuArray [15] = deseseis;
        meuArray [16] = desesete;
        meuArray [17] = desoto;
        meuArray [18] = desenove;
        meuArray [19] = vinte;
                 
         
          int total = um +dois+ tres + quatro + cinco + seis + sete + oito +
                  nove + dez + onze + doze  + treze + quatoze + quise +deseseis +desesete + desoto +desenove + vinte;
            //     System.out.print(um);

              
               
               
                
                
           


             /*  String um =  jTextField8.getText();
               String dois = jTextField9.getText();
               String tres = jTextField10.getText();
               String quatro = jTextField11.getText();
               
               int UM = Integer.parseInt(um);
               int DOIS = Integer.parseInt(dois);
               int TRES =  Integer.parseInt(tres);
               int QUATRO =  Integer.parseInt(quatro);
               int RESUTADO = UM * DOIS;
               System.out.print(RESUTADO);
               jTextField12.setText(""+RESUTADO); */
             
            }
            
        } catch (Exception ex) {
            Logger.getLogger(PaginaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }     }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TxT_Pedididos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonNegocio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemCadUsuario;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemTelaBemVindo;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextpro;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel jldata;
    private javax.swing.JLabel jlhora;
    private javax.swing.JTable jtTabelaP;
    private javax.swing.JLabel txT_Faturamento;
    private javax.swing.JLabel txT_Total;
    // End of variables declaration//GEN-END:variables

    private String[] String(String Pesquisar) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
